import { Inter } from "next/font/google";
import "./globals.css";
// import Mynav from "../comCompo/Mynav.jsx";
import Script from "next/script";
import Fullnav from "/comCompo/Fullnav";
import NextTopLoader from 'nextjs-toploader';
import { Providers } from "./providers";
import Footer from "/comCompo/Footer";
// import Theme from './lib/Theme'
import { Theme } from '@radix-ui/themes';
// import { ThemeSwitcher } from "./Components1/ThemeSwitcher";
import { Suspense } from "react";
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    template: '%s | Gohil',
    default:'AKASH'
  },
  description: "Generated by create next app",
  keywords:['Akash gohil','akash gohil portfolio','gohil','akash','software engineer','surat'],

   creator:'akash'
};

export const viewport = {
  width: 'device-width',
 
  // Also supported by less commonly used
  // interactiveWidget: 'resizes-visual',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta
  name="viewport"
  content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
/>
<link rel="icon" href="/logo.png" sizes="any" />
      <body className={`${inter.className} relative bg-white dark:bg-gray-800 dark:text-white`}>
        <Providers>
          <NextTopLoader color="red" height={2} showSpinner={false} />
          <Fullnav />
         <Suspense fallback={<Loading/>}>

          {children}
          </Suspense>

          <Footer />
        </Providers>
      </body>
    </html>
  );
}
